INSERT INTO military_bases (id, code, name, location, commanding_officer, status) VALUES (1, 'BASE-LIBERTY', 'Fort Liberty Command', 'Fayetteville, North Carolina', 'Gen. Marcus Vance', 'ACTIVE');
INSERT INTO military_bases (id, code, name, location, commanding_officer, status) VALUES (2, 'BASE-PENDLETON', 'Camp Pendleton Marine Base', 'Oceanside, California', 'Col. Sarah Jenkins', 'ACTIVE');
INSERT INTO military_bases (id, code, name, location, commanding_officer, status) VALUES (3, 'BASE-NELLIS', 'Nellis Strategic Air Base', 'Clark County, Nevada', 'Maj. Gen. David Sterling', 'ACTIVE');
INSERT INTO military_bases (id, code, name, location, commanding_officer, status) VALUES (4, 'BASE-RAMSTEIN', 'Ramstein Allied Support Base', 'Rhineland-Palatinate, Germany', 'Brig. Gen. Elena Rostova', 'ACTIVE');
INSERT INTO military_bases (id, code, name, location, commanding_officer, status) VALUES (5, 'BASE-NORFOLK', 'Naval Station Norfolk Command', 'Norfolk, Virginia', 'Rear Adm. Thomas Blake', 'ACTIVE');

INSERT INTO users (id, username, password, full_name, military_rank, service_number, email, role, base_id, status) VALUES (1, 'admin', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'Gen. Alexander Hayes', 'General (4-Star)', 'DOD-HQ-001', 'admin@mams.mil', 'ADMIN', NULL, 'ACTIVE');
INSERT INTO users (id, username, password, full_name, military_rank, service_number, email, role, base_id, status) VALUES (2, 'commander_liberty', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'Gen. Marcus Vance', 'Lieutenant General', 'USA-LIB-104', 'vance.m@liberty.mil', 'BASE_COMMANDER', 1, 'ACTIVE');
INSERT INTO users (id, username, password, full_name, military_rank, service_number, email, role, base_id, status) VALUES (3, 'commander_pendleton', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'Col. Sarah Jenkins', 'Colonel', 'USMC-PEN-209', 'jenkins.s@pendleton.mil', 'BASE_COMMANDER', 2, 'ACTIVE');
INSERT INTO users (id, username, password, full_name, military_rank, service_number, email, role, base_id, status) VALUES (4, 'logistics_liberty', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'Maj. Robert Evans', 'Major', 'USA-LOG-512', 'evans.r@logistics.mil', 'LOGISTICS_OFFICER', 1, 'ACTIVE');
INSERT INTO users (id, username, password, full_name, military_rank, service_number, email, role, base_id, status) VALUES (5, 'logistics_pendleton', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'Capt. Emily Rodriguez', 'Captain', 'USMC-LOG-881', 'rodriguez.e@logistics.mil', 'LOGISTICS_OFFICER', 2, 'ACTIVE');
INSERT INTO users (id, username, password, full_name, military_rank, service_number, email, role, base_id, status) VALUES (6, 'commander_nellis', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'Maj. Gen. David Sterling', 'Major General', 'USAF-NEL-303', 'sterling.d@nellis.mil', 'BASE_COMMANDER', 3, 'ACTIVE');

INSERT INTO asset_categories (id, name, code, description) VALUES (1, 'Weapons', 'CAT-WPN', 'Assault rifles, carbines, sniper platforms, tactical sidearms, and crew-served heavy weapons');
INSERT INTO asset_categories (id, name, code, description) VALUES (2, 'Vehicles', 'CAT-VEH', 'Armored fighting vehicles, main battle tanks, Joint Light Tactical Vehicles, and troop transports');
INSERT INTO asset_categories (id, name, code, description) VALUES (3, 'Ammunition', 'CAT-AMM', 'Live munitions, high-explosive artillery rounds, guided anti-tank missiles, and small-caliber cartridges');
INSERT INTO asset_categories (id, name, code, description) VALUES (4, 'Tactical Communications', 'CAT-COM', 'Multiband cryptographic radios, satellite uplinks, mesh networking nodes, and command terminals');
INSERT INTO asset_categories (id, name, code, description) VALUES (5, 'Aviation & UAVs', 'CAT-AIR', 'Tactical reconnaissance drones, electronic surveillance UAVs, transport helicopters, and attack platforms');
INSERT INTO asset_categories (id, name, code, description) VALUES (6, 'Heavy Equipment', 'CAT-HEV', 'Mobile radar stations, field generators, armored recovery systems, and engineering logistics gear');

INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (1, 'WPN-M4A1-TAC', 'M4A1 Tactical Carbine 5.56mm', 1, 'Units', 1450.00, 'Standard infantry service rifle with optical rail and selector switch.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (2, 'WPN-M240B-MG', 'M240B Medium Machine Gun 7.62mm', 1, 'Units', 6800.00, 'Crew-served gas-operated machine gun for high-volume suppressing fire.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (3, 'WPN-BARRETT-M82', 'Barrett M82A1 .50 BMG Anti-Materiel', 1, 'Units', 11200.00, 'Long-range precision heavy rifle for anti-equipment and defensive operations.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (4, 'VEH-JLTV-ARM', 'Joint Light Tactical Vehicle (JLTV)', 2, 'Vehicles', 385000.00, '4x4 heavily armored tactical vehicle with integrated blast protection.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (5, 'VEH-M2A3-BRADLEY', 'M2A3 Bradley Infantry Fighting Vehicle', 2, 'Vehicles', 3200000.00, 'Tracked armored combat vehicle equipped with 25mm Bushmaster autocannon & TOW missiles.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (6, 'VEH-M1A2-SEP3', 'M1A2 Abrams SEPv3 Main Battle Tank', 2, 'Vehicles', 9800000.00, 'Third-generation main battle tank with 120mm smoothbore cannon and reactive armor.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (7, 'AMM-556-NATO', '5.56x45mm NATO Ball M855A1 (10,000 Rds)', 3, 'Crates', 4500.00, 'High-velocity enhanced performance infantry ammunition crate.', TRUE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (8, 'AMM-762-LINKED', '7.62x51mm NATO Linked Belts (5,000 Rds)', 3, 'Crates', 3800.00, 'Belted ammunition for vehicle and infantry medium machine gun emplacements.', TRUE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (9, 'AMM-JAVELIN-MSL', 'FGM-148 Javelin Anti-Tank Missile', 3, 'Missiles', 178000.00, 'Fire-and-forget man-portable lock-on top-attack anti-armor missile round.', TRUE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (10, 'COM-PRC-152A', 'AN/PRC-152A Handheld Tactical Radio', 4, 'Units', 6200.00, 'Type-1 encrypted multiband handheld transceiver with GPS and satellite capability.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (11, 'COM-SAT-TERMV3', 'Mil-Satcom Tactical Command Terminal', 4, 'Systems', 48000.00, 'High-bandwidth portable satellite ground station for battlefield command networking.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (12, 'AIR-MQ9-REAPER', 'MQ-9 Reaper Tactical Strike UAV', 5, 'Aircraft', 16500000.00, 'Remotely piloted aircraft system for intelligence, surveillance, and precision strikes.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (13, 'AIR-BLACKHAWK-UH60', 'UH-60M Black Hawk Utility Helicopter', 5, 'Aircraft', 21000000.00, 'Four-blade, twin-engine medium-lift tactical transport and assault helicopter.', FALSE);
INSERT INTO assets (id, asset_code, name, category_id, unit_of_measure, unit_price, description, is_expendable) VALUES (14, 'HEV-GEN-60KW', '60kW Tactical Quiet Generator Plant', 6, 'Units', 24500.00, 'Ruggedized mobile diesel generator for command centers and radar arrays.', FALSE);

INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (1, 1, 1, 350, 80, 20, 15, 65, 0, 435, 370);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (2, 1, 2, 45, 10, 5, 2, 12, 0, 58, 46);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (3, 1, 4, 30, 8, 4, 2, 10, 0, 40, 30);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (4, 1, 5, 14, 2, 0, 1, 4, 0, 15, 11);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (5, 1, 7, 200, 50, 10, 20, 0, 45, 195, 195);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (6, 1, 9, 35, 10, 0, 5, 0, 8, 32, 32);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (7, 1, 10, 120, 30, 15, 10, 42, 0, 155, 113);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (8, 1, 12, 6, 2, 0, 1, 2, 0, 7, 5);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (9, 2, 1, 280, 50, 15, 10, 50, 0, 335, 285);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (10, 2, 2, 35, 8, 2, 0, 8, 0, 45, 37);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (11, 2, 3, 12, 4, 0, 1, 3, 0, 15, 12);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (12, 2, 4, 24, 6, 2, 0, 6, 0, 32, 26);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (13, 2, 7, 180, 40, 20, 5, 0, 30, 205, 205);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (14, 2, 8, 90, 20, 5, 0, 0, 15, 100, 100);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (15, 2, 10, 95, 20, 10, 5, 30, 0, 120, 90);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (16, 2, 13, 8, 2, 0, 0, 3, 0, 10, 7);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (17, 3, 1, 150, 30, 5, 0, 25, 0, 185, 160);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (18, 3, 10, 80, 15, 5, 0, 20, 0, 100, 80);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (19, 3, 11, 10, 2, 1, 0, 3, 0, 13, 10);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (20, 3, 12, 12, 4, 1, 0, 4, 0, 17, 13);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (21, 3, 14, 18, 5, 0, 0, 4, 0, 23, 19);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (22, 4, 1, 200, 40, 10, 5, 40, 0, 245, 205);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (23, 4, 4, 18, 4, 1, 0, 5, 0, 23, 18);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (24, 4, 7, 150, 30, 5, 0, 0, 20, 165, 165);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (25, 4, 10, 70, 15, 5, 2, 22, 0, 88, 66);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (26, 4, 13, 6, 2, 0, 0, 2, 0, 8, 6);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (27, 5, 1, 180, 25, 5, 0, 30, 0, 210, 180);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (28, 5, 2, 25, 5, 0, 0, 6, 0, 30, 24);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (29, 5, 10, 60, 10, 0, 0, 15, 0, 70, 55);
INSERT INTO base_inventories (id, base_id, asset_id, opening_balance, total_purchased, total_transferred_in, total_transferred_out, assigned_quantity, expended_quantity, closing_balance, current_balance) VALUES (30, 5, 11, 8, 3, 0, 0, 2, 0, 11, 9);

INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (1, 'PO-2026-MIL-8001', 1, 1, 80, 1450.00, 116000.00, 'Colt Defense Corp', '2026-08-15 09:30:00', 4, 'RECEIVED', 'Procured standard issue rifles for 82nd Airborne Division rotation.');
INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (2, 'PO-2026-MIL-8002', 1, 4, 8, 385000.00, 3080000.00, 'Oshkosh Defense LLC', '2026-08-20 11:15:00', 4, 'RECEIVED', 'New JLTV variant with upgraded composite armor plates.');
INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (3, 'PO-2026-MIL-8003', 1, 7, 50, 4500.00, 225000.00, 'Lake City Army Ammunition Plant', '2026-08-25 14:00:00', 4, 'RECEIVED', 'Q3 regular ammunition replenishment for training and operational reserve.');
INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (4, 'PO-2026-MIL-8004', 2, 1, 50, 1450.00, 72500.00, 'Colt Defense Corp', '2026-08-28 10:00:00', 5, 'RECEIVED', 'Marine Expeditionary Unit tactical weapons modernization.');
INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (5, 'PO-2026-MIL-8005', 2, 7, 40, 4500.00, 180000.00, 'Winchester Defense Munitions', '2026-09-02 13:45:00', 5, 'RECEIVED', 'Live fire training stockpile for Camp Pendleton ranges.');
INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (6, 'PO-2026-MIL-8006', 3, 12, 4, 16500000.00, 66000000.00, 'General Atomics Aeronautical', '2026-09-05 08:30:00', 6, 'RECEIVED', 'Reaper Block 5 UAV addition for Red Flag joint tactical exercise.');
INSERT INTO purchases (id, purchase_order_number, base_id, asset_id, quantity, unit_cost, total_cost, supplier, purchase_date, received_by_user_id, status, notes) VALUES (7, 'PO-2026-MIL-8007', 4, 10, 15, 6200.00, 93000.00, 'L3Harris Tactical Communications', '2026-09-10 15:20:00', 1, 'RECEIVED', 'Secure encrypted VHF/UHF tactical radio transceivers.');

INSERT INTO transfers (id, transfer_number, source_base_id, destination_base_id, asset_id, quantity, status, initiated_by_user_id, received_by_user_id, dispatched_at, completed_at, reason_or_mission) VALUES (1, 'TRF-2026-9001', 1, 2, 1, 15, 'COMPLETED', 4, 5, '2026-09-01 08:00:00', '2026-09-02 16:30:00', 'Inter-base support for joint USMC/Army rapid deployment training.');
INSERT INTO transfers (id, transfer_number, source_base_id, destination_base_id, asset_id, quantity, status, initiated_by_user_id, received_by_user_id, dispatched_at, completed_at, reason_or_mission) VALUES (2, 'TRF-2026-9002', 2, 1, 7, 20, 'COMPLETED', 5, 4, '2026-09-04 10:00:00', '2026-09-05 14:00:00', 'Ammo balance re-allocation due to impending exercise at Fort Liberty.');
INSERT INTO transfers (id, transfer_number, source_base_id, destination_base_id, asset_id, quantity, status, initiated_by_user_id, received_by_user_id, dispatched_at, completed_at, reason_or_mission) VALUES (3, 'TRF-2026-9003', 1, 3, 10, 5, 'COMPLETED', 4, 6, '2026-09-08 11:30:00', '2026-09-09 12:00:00', 'Transfer of cryptographic communications units for airbase security squad.');
INSERT INTO transfers (id, transfer_number, source_base_id, destination_base_id, asset_id, quantity, status, initiated_by_user_id, received_by_user_id, dispatched_at, completed_at, reason_or_mission) VALUES (4, 'TRF-2026-9004', 1, 4, 4, 1, 'COMPLETED', 4, 1, '2026-09-12 09:00:00', '2026-09-14 18:00:00', 'Airlift deployment of armored JLTV to Ramstein for NATO logistics inspection.');
INSERT INTO transfers (id, transfer_number, source_base_id, destination_base_id, asset_id, quantity, status, initiated_by_user_id, received_by_user_id, dispatched_at, completed_at, reason_or_mission) VALUES (5, 'TRF-2026-9005', 2, 4, 10, 5, 'COMPLETED', 5, 1, '2026-09-18 13:00:00', '2026-09-20 15:30:00', 'Allied communication protocol integration support.');

INSERT INTO asset_assignments (id, assignment_code, base_id, asset_id, assigned_to_name, assigned_to_rank, assigned_to_service_id, unit_or_squadron, quantity, assigned_date, expected_return_date, condition_on_issue, status, assigned_by_user_id, notes) VALUES (1, 'ASG-2026-101', 1, 1, 'Staff Sgt. Nathan Cole', 'Staff Sergeant', 'USA-INF-4482', '82nd Airborne Division / 2nd Brigade', 1, '2026-09-01 09:00:00', '2026-10-01', 'EXCELLENT', 'ACTIVE', 2, 'Primary weapon issued for field deployment.');
INSERT INTO asset_assignments (id, assignment_code, base_id, asset_id, assigned_to_name, assigned_to_rank, assigned_to_service_id, unit_or_squadron, quantity, assigned_date, expected_return_date, condition_on_issue, status, assigned_by_user_id, notes) VALUES (2, 'ASG-2026-102', 1, 4, '1st Lt. Andrea Gomez', '1st Lieutenant', 'USA-ARM-1193', '3rd Armored Cavalry Recon Unit', 1, '2026-09-03 10:30:00', '2026-11-15', 'EXCELLENT', 'ACTIVE', 2, 'Command JLTV vehicle assigned for tactical reconnaissance.');
INSERT INTO asset_assignments (id, assignment_code, base_id, asset_id, assigned_to_name, assigned_to_rank, assigned_to_service_id, unit_or_squadron, quantity, assigned_date, expected_return_date, condition_on_issue, status, assigned_by_user_id, notes) VALUES (3, 'ASG-2026-103', 1, 10, 'Sgt. Lucas Vance', 'Sergeant', 'USA-SIG-7721', 'Signal Intelligence Detachment Delta', 2, '2026-09-05 14:00:00', '2026-09-30', 'EXCELLENT', 'ACTIVE', 4, 'Encrypted handheld radios for perimeter surveillance.');
INSERT INTO asset_assignments (id, assignment_code, base_id, asset_id, assigned_to_name, assigned_to_rank, assigned_to_service_id, unit_or_squadron, quantity, assigned_date, expected_return_date, condition_on_issue, status, assigned_by_user_id, notes) VALUES (4, 'ASG-2026-104', 2, 1, 'Cpl. Jason Taylor', 'Corporal', 'USMC-INF-9820', '1st Marine Division / Charlie Company', 1, '2026-09-06 08:00:00', '2026-10-15', 'EXCELLENT', 'ACTIVE', 3, 'Standard weapon issue for amphibious training detachment.');
INSERT INTO asset_assignments (id, assignment_code, base_id, asset_id, assigned_to_name, assigned_to_rank, assigned_to_service_id, unit_or_squadron, quantity, assigned_date, expected_return_date, condition_on_issue, status, assigned_by_user_id, notes) VALUES (5, 'ASG-2026-105', 2, 2, 'Gunnery Sgt. Derek Hall', 'Gunnery Sergeant', 'USMC-WEP-3310', 'Heavy Weapons Platoon', 1, '2026-09-08 11:00:00', '2026-10-30', 'EXCELLENT', 'ACTIVE', 3, 'Medium machine gun for tactical support post.');

INSERT INTO asset_expenditures (id, expenditure_code, base_id, asset_id, quantity, expended_date, mission_or_exercise, authorized_officer, recorded_by_user_id, remarks) VALUES (1, 'EXP-2026-501', 1, 7, 30, '2026-09-05 16:00:00', 'Exercise Iron Saber - Infantry Marksmanship Qualification', 'Gen. Marcus Vance', 4, '300,000 rounds of 5.56mm expended across 4 battalions with 98% qualification rate.');
INSERT INTO asset_expenditures (id, expenditure_code, base_id, asset_id, quantity, expended_date, mission_or_exercise, authorized_officer, recorded_by_user_id, remarks) VALUES (2, 'EXP-2026-502', 1, 9, 4, '2026-09-10 14:30:00', 'Operation Northern Strike - Heavy Armor Denial Drill', 'Gen. Marcus Vance', 4, '4 Javelin missiles fired against remote target tanks. 4 direct hits confirmed.');
INSERT INTO asset_expenditures (id, expenditure_code, base_id, asset_id, quantity, expended_date, mission_or_exercise, authorized_officer, recorded_by_user_id, remarks) VALUES (3, 'EXP-2026-503', 2, 7, 20, '2026-09-12 11:00:00', 'Exercise Steel Knight - Live Fire Assault Course', 'Col. Sarah Jenkins', 5, '200,000 rounds expended during combined arms assault simulations.');
INSERT INTO asset_expenditures (id, expenditure_code, base_id, asset_id, quantity, expended_date, mission_or_exercise, authorized_officer, recorded_by_user_id, remarks) VALUES (4, 'EXP-2026-504', 2, 8, 10, '2026-09-15 15:45:00', 'Camp Pendleton Heavy Gunner Range Certification', 'Col. Sarah Jenkins', 5, 'M240B continuous suppressive fire training drills.');

INSERT INTO audit_logs (id, timestamp, user_id, username, role, action, entity_name, entity_id, details, ip_address) VALUES (1, '2026-08-15 09:30:00', 4, 'logistics_liberty', 'LOGISTICS_OFFICER', 'PURCHASE_RECORDED', 'Purchase', 'PO-2026-MIL-8001', 'Recorded purchase of 80 units of M4A1 Tactical Carbine from Colt Defense Corp.', '127.0.0.1');
INSERT INTO audit_logs (id, timestamp, user_id, username, role, action, entity_name, entity_id, details, ip_address) VALUES (2, '2026-08-20 11:15:00', 4, 'logistics_liberty', 'LOGISTICS_OFFICER', 'PURCHASE_RECORDED', 'Purchase', 'PO-2026-MIL-8002', 'Recorded purchase of 8 units of JLTV from Oshkosh Defense LLC.', '127.0.0.1');
INSERT INTO audit_logs (id, timestamp, user_id, username, role, action, entity_name, entity_id, details, ip_address) VALUES (3, '2026-09-01 08:00:00', 4, 'logistics_liberty', 'LOGISTICS_OFFICER', 'TRANSFER_INITIATED', 'Transfer', 'TRF-2026-9001', 'Dispatched 15 units of M4A1 Carbine from Fort Liberty to Camp Pendleton.', '127.0.0.1');
INSERT INTO audit_logs (id, timestamp, user_id, username, role, action, entity_name, entity_id, details, ip_address) VALUES (4, '2026-09-02 16:30:00', 5, 'logistics_pendleton', 'LOGISTICS_OFFICER', 'TRANSFER_COMPLETED', 'Transfer', 'TRF-2026-9001', 'Received and verified 15 units of M4A1 Carbine at Camp Pendleton.', '127.0.0.1');
INSERT INTO audit_logs (id, timestamp, user_id, username, role, action, entity_name, entity_id, details, ip_address) VALUES (5, '2026-09-05 16:00:00', 4, 'logistics_liberty', 'LOGISTICS_OFFICER', 'ASSET_EXPENDED', 'Expenditure', 'EXP-2026-501', 'Recorded expenditure of 30 crates of 5.56mm Ammo for Exercise Iron Saber.', '127.0.0.1');
